### ISSUE TITLE
Milestones functions

### ISSUE THREAD

**Issue by ChadGoymer** [ChadGoymer/githapi#144]
## Description

Add functions for creating, updating, viewing and deleting milestones.

## Proposed Solution

Need to implement the following functions:

- [x] `view_milestones()` which returns a tibble summarising the milestones within a repo or on an issue or pull request.
- [x] `view_milestone()` which returns a list of properties for a single milestone within a repo.
- [x] `create_milestone()` which creates a new milestone within a repo and returns a list of its properties.
- [x] `update_milestone()` which updates a milestone within a repo and returns a list of its properties.
- [x] `delete_milestone()` which deletes a milestone within a repo
